---
- name: handle docker_virtualisation
  set_fact: docker={{ ansible_virtualization_type is defined and ansible_virtualization_type == 'docker' and ansible_virtualization_role == 'guest' }}

- name: Restart Service 'docker'
  systemd: state=restarted daemon_reload=yes name=docker
  notify: restart docker
  become: true
  when: not ansible_check_mode and not docker

- name: restart docker
  service: name={{ docker_service_name }} state=restarted

- name: reload docker
  service: name={{ docker_service_name }} state=reloaded
