FROM debian/jessie

RUN apt-get update 
RUN apt-get install make
COPY deployment.tar.gz /opt/deployment.tar.gz
RUN cd /opt && tar xvfz deployment.tar.gz

COPY docker-entrypoint.sh /docker-entrypoint.sh

RUN mkdir -p /opt/test-config/group_vars
COPY test-config/inventory /opt/test-config
COPY test-config/docker /opt/test-config/group_vars
COPY ansible.cfg  /opt/ansible.cfg

RUN sed -i -e "s@http_proxy: \"http://localhost:80\"@http_proxy: \"$http_proxy\"@g" /opt/test-config/group_vars/docker
RUN sed -i -e "s@https_proxy: \"http://localhost:80\"@https_proxy: \"$https_proxy\"@g" /opt/test-config/group_vars/docker

RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

